controller_joint_names: ['', 'front_right_steering_joint', 'front_right_traction_joint', 'front_left_steering_joint', 'front_left_traction_joint', 'rear_right_traction_joint', 'rear_left_traction_joint', ]
